#!/usr/bin/env bash
# Web debugging detect what's wrong on the web server

sudo apt-get update -y
sudo apt-get install nginx -y

sudo systemctl enable nginx

cat <<EOF | sudo tee /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;
    root /var/www/html;

    index index.html index.htm index.nginx-debian.html;

    location / {
        try_files \$uri \$uri/ =404;
    }
}
EOF

sudo nginx -t

sudo systemctl restart nginx

sudo systemctl status nginx
sudo netstat -tuln | grep :80
