#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
counter=1
while [ $counter -le 100 ]; do
	if [ $((counter % 3)) -eq 0 ] && [ $((counter % 5)) -eq 0 ]; then 
	       	echo "FizzBuzz"
	elif [ $((counter % 3)) -eq 0 ]; then
     		echo "Fizz"
	elif [ $((counter % 5)) -eq 0 ]; then
		echo "Buzz"
	else
		echo "$counter"
       	fi 
       	((counter++))
done
