#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
counter=1
while [ $counter -lt 21 ]; do
	echo "$counter"
	if [ $counter = 4  ]; then
		echo "bad luck from China"
	elif [ $counter = 9 ]; then
		echo "bad luck from Japan"
	elif [ $counter = 17 ]; then
		echo "bad luck from Italy"
       	fi
	((counter++))
done


