#!/usr/bin/env bash
# This script displays the content of the current directory

for file in *; do
    if [[ -f "$file" && ! "$file" == -* ]]; then
        filename="${file#*-}"
        echo "$filename"
    fi
done

