#!/usr/bin/env bash

# This script displays the content of the current directory
# In a list format, showing only the part of the name after the first dash

for file in *; do
    if [[ -f "$file" && ! "$file" == -* ]]; then
        filename="${file#*-}"
        echo "$filename"
    fi
done

