#!/user/bin/env bash
# let's intall firewall on our server

sudo apt install -y ufw
sudo ufw default allow outgoing
sudo ufw defult deny incoming
sudo ufw allow 22/tcp
sudo ufw allow 43
sudo ufw allow 80
echo "y" | sudo ufw enable